baseURL = 'https://lostnatsu.com/'

languageCode = 'zh'
defaultContentLanguage = 'zh'
title = "浴憶"
theme = 'PaperMod'

[params.homeInfoParams]
Title = '太陽強烈 水波溫柔'
Content = '洗洗做夢'

[[params.socialIcons]]
name = "email"
url = "mailto:helloboy3x@gmail.com"

[[menu.main]]
name = "碎片"
url = "archives"
weight = 10

[[menu.main]]
name = "搜尋"
url = "search/"
weight = 20

[[menu.main]]
name = "這誰,這啥"
url = "about"
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe= true
